server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Security Related Configuration

#Manually spring ke liye Username and Password set kr rahe hai
  security:
    user:
      name: alpha
      password: alpha123